node {
   def mvnHome = tool 'M3'
   stage('Preparation') { // for display purposes
      // Get some code from a GitHub repository
      // Get the Maven tool.
      // ** NOTE: This 'M3' Maven tool must be configured
      // **       in the global configuration.           
       git branch: 'master',
       credentialsId: 'f30cf8ec-04bd-4002-89ac-8aaeeb7a1df8',
       url: 'https://gitlab.com/rortizrojo/tfm-spark.git'
   }
   stage('Build') {
      // Run the maven build
      withEnv(["MVN_HOME=$mvnHome"]) {
         if (isUnix()) {
            sh '"$MVN_HOME/bin/mvn" -Dmaven.test.failure.ignore clean package'
         } else {
            bat(/"%MVN_HOME%\bin\mvn" -Dmaven.test.failure.ignore clean package/)
         }
      }
   }
   stage('Creation Azure Storage'){
      sh 'cd scripts/azure/storage/'
      sh 'ls -la'
      sh 'deploy.sh -i 5a08e9e0-83ee-4188-8fc2-18e16c7db524 -g resourceGroup -n desplieguePrueba -l westeurope'
   }
   stage('Results') {
      junit '**/target/surefire-reports/TEST-*.xml'
      archiveArtifacts 'target/*.jar'
   }
}
